version: "3.7"
services:
  postgres:
    image: debezium/postgres:13
    platform: linux/amd64
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U postgresuser -d payment_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=payment_db
      - PGPASSWORD=postgrespw
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
    - 9092:9092
  akhq:
    image: tchiotludo/akhq
    ports:
      - 9000:8080
    links:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            cdc-plaintext-cluster:
              properties:
                bootstrap.servers: "kafka:9092"